---
Name: nswdpc-content-boilerplate
---
Page:
  extensions:
    - DNADesign\Elemental\Extensions\ElementalPageExtension
---
Name: nswdpc-content-sitemaps
After:
  - '#googlesitemaps'
---
Wilr\GoogleSitemaps\GoogleSitemap:
  enabled: true
  objects_per_sitemap: 1000
  google_notification_enabled: true
  bing_notification_enabled: true
  use_show_in_search: true
