---
Name: nswdpc-content-boilerplate
---
Page:
  extensions:
    - DNADesign\Elemental\Extensions\ElementalPageExtension
---
Name: app-content-workflow
---
Symbiote\AdvancedWorkflow\Actions\NotifyUsersWorkflowAction:
  whitelist_template_variables: true
Page:
  extensions:
    - Symbiote\AdvancedWorkflow\Extensions\WorkflowEmbargoExpiryExtension
---
Name: nswdpc-content-sitemaps
After:
  - '#googlesitemaps'
---
Wilr\GoogleSitemaps\GoogleSitemap:
  enabled: true
  objects_per_sitemap: 1000
  google_notification_enabled: true
  bing_notification_enabled: true
  use_show_in_search: true
---
Name: 'nswdpc-content-taxonomy-icon'
After:
  - '#nswdpc-taxonomy-icon'
---
# use CSS as the default icon system
SilverStripe\Taxonomy\TaxonomyTerm:
  is_upload: false
  is_css: true
  is_filename: false
  filename_path: ''
---
Name: nswdpc-content-userforms
After:
  - '#userformsconfig'
---
SilverStripe\UserForms\Model\UserDefinedForm:
  block_default_userforms_css: true

SilverStripe\UserForms\Control\UserDefinedFormController:
  disable_form_content_shortcode: true

SilverStripe\UserForms\Model\Recipient\EmailRecipient:
  allow_unbound_recipient_fields: true
